version: "3.8"

services:
  db:
    image: mysql:8.0.23
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_app:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - symfony

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - symfony

  php:
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - symfony_dockerized_app_sync:/var/www/symfony/
    networks:
      - symfony
  nginx:
    build:
      context: ./nginx
    volumes:
      - symfony_dockerized_app_sync:/var/www/symfony/
    ports:
      - 80:80
    networks:
      - symfony
    env_file:
      - .env.nginx.local

  cron:
    container_name: news-cron
    build: ./cron
    volumes:
      - ../:/var/www
      - ./log/cron:/var/log/cron

volumes:
  symfony_dockerized_app_sync:
    external: true
  db_app:


networks:
  symfony:
